### ISSUE TITLE
Not working with Grav's Admin Panel

### ISSUE THREAD

**Issue by jpfleury** [Sommerregen/grav-plugin-archive-plus#4]
The plugin Archive Plus can't be configured using the new [Grav's Admin Panel](https://github.com/getgrav/grav-plugin-admin). For example, if we go to the settings page of the plugin (url `/admin/plugins/archive_plus`) and click on *Save*, there's the following error:

> **Validation failed:** items is not defined in blueprints

According to a Grav developer: "These plugins just need to get updated with appropriate blueprint files so they will work in the admin plugin."

My config: Grav v0.9.39, Admin Panel v0.4.2, Archive Plus v1.3.1

**Comment by Sommerregen** [comment]
Ok, will do my best. Thanks!
