### ISSUE TITLE
Not working with GRAV 1.0+

### ISSUE THREAD

**Issue by marsien** [Sommerregen/grav-plugin-archive-plus#6]
As written in this [issue](https://github.com/getgrav/grav-plugin-archives/issues/1) for the **archive** plugin, I have a problem to use the **archive plus** plugin with GRAV 1.0+.

At the beginning, I tought the problem went from the choice of french language of my blog. But I have the same problem with a new install of GRAV in English, without language selection.

Even if I choose a month or a year, all articles are returned as results.

**Comment by Sommerregen** [comment]
Hi @marsien ,

thanks for opening the issue. Unfortunately I haven't had the time yet to search for the bug and the user folder your provided always shut down my test install... However, I hope I have this week. If I have anything new, I'll let you know.

**Comment by Sommerregen** [comment]
Sorry for taking it to long to fix. I just noticed that it happens alos on my test install. Will investigate further and will be fixed right after I finished my current project.

**Comment by Sommerregen** [comment]
Ok, got it. As described here #7 there is a bug in the Archive Plus plugin being responsible for #6. To be precise [L76 of archive_plus.php](https://github.com/Sommerregen/grav-plugin-archive-plus/blob/master/archive_plus.php#L76) should be

``` php
$archive = $this->grav['language']->translate(['PLUGINS.ARCHIVE_PLUS.NAME']);
```

I will release a new version soon with the fix and additional features. Please be patient or fix it in the meantime for yourself.

**Comment by marsien** [comment]
thx a lot. It works for me!
